Allow configuration checks to be turned off
theforeman/puppet-dns pull request #178
Opened 2020-10-29 20:37 UTC by coreone

2020-10-29 20:50 UTC, alexjfisher approved these changes
LGTM other than a couple of very minor style suggestions.

2020-10-29 20:50 UTC, alexjfisher commented on spec/classes/dns_init_spec.rb
> +        let :params do
For consistency with the other tests, maybe
`let(:params) { {:config_check => false} }`??

2020-10-29 20:50 UTC, alexjfisher commented on spec/classes/dns_init_spec.rb
> +            .with_validate_cmd(nil)
Consider `.without_validate_cmd`

2020-10-30 08:42 UTC, alexjfisher requested changes

2020-10-30 08:42 UTC, alexjfisher commented on manifests/init.pp
> +  Boolean $config_check                                             = $dns::params::config_check,
You need to add a puppet strings style documentation comment.

2020-10-30 22:08 UTC, alexjfisher approved these changes

2020-11-01 12:22 UTC, ekohl approved these changes

2020-11-01 12:23 UTC, merged