Drop EL6 and Debian 8 support
theforeman/puppet-dns pull request #193
Opened 2021-07-13 19:58 UTC by ehelms

2021-07-19 13:09 UTC, ehelms commented
@ekohl Can you review this? Since we are releasing a new major version this should go in.

2021-07-19 14:12 UTC, ekohl requested changes
Can we also drop Ubuntu 16.04 (EOL since April 2021) while we do a major bump?

2021-07-19 14:12 UTC, ekohl commented on metadata.json
> -    {
Can we keep Fedora in and add 33/34?

2021-07-19 14:32 UTC, ekohl commented on metadata.json
> +        "34"
```suggestion
        "34"
      ]
```

2021-07-20 19:42 UTC, ehelms commented
Removed the changes to Fedora given the testing on 33 and 34 does not work yet.

2021-07-21 10:04 UTC, ekohl approved these changes

2021-07-21 10:05 UTC, merged