Add support for Ubuntu Jammy (22.04)
theforeman/puppet-dns pull request #228
Opened 2023-03-14 15:15 UTC by kajinamit

This change introduces initial support for Ubuntu Jammy.

Fixes: #227

2023-03-14 15:34 UTC, ekohl requested changes

2023-03-14 15:34 UTC, ekohl commented on manifests/params.pp
> +        default  => '/usr/sbin/named-checkconf'
I think this fails on missing commas:
```suggestion
        'Ubuntu' => if versioncmp($facts['os']['release']['major'], '22.04') >= 0 { '/usr/bin/named-checkconf' } else { '/usr/sbin/named-checkconf' },
        default  => '/usr/sbin/named-checkconf',
```

2023-03-14 16:01 UTC, kajinamit commented on manifests/params.pp
> +        default  => '/usr/sbin/named-checkconf'
Oops. Fixed these.

2023-03-14 16:04 UTC, merged

2023-03-15 00:47 UTC, kajinamit commented
@ekohl Thanks for merging this PR. Do you mind creating a new release ?

2023-03-15 10:36 UTC, ekohl commented
https://github.com/theforeman/puppet-dns/pull/229